name: velocimart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8


  get: ^4.6.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  
  flutter_lints: ^4.0.0

flutter:
  
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/fonts/
    - assets/images/
    - assets/icons/


  fonts:
    - family:
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 300
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 200
          style: italic



